### ISSUE TITLE
"constructor" in example

### ISSUE THREAD

**Issue by boneskull** [Losant/losant-sdk-js#3]
In `README.md`'s example:

```javascript
var Device = require('losant-sdk-js').Device;

// Construct device.
var device = new Device({
  id: 'my-device-id',
  key: 'my-app-access-key',
  secret: 'my-app-access-secret'
});
```

The above is misleading, since `Device` is not actually a constructor; `new` is unnecessary.

**Comment by InconceivableDuck** [comment]
Good catch. I have removed 'new' from the readme and the examples.

**Comment by InconceivableDuck** [comment]
I like adding a callback to connect. Will implement that. Will also update examples to recommend calling device.isConnected() prior to sending state.
